spring.application.name=gestion-guias
# Configuración del servidor
server.port=8080

# Credenciales de AWS S3 (Pega tus datos reales de la foto aquí)
aws.access.key=ASIAWHU3SSG3E4HXRHFK
aws.secret.key=/AsEBg/Kjn1I2g7ISAQ26Qhmdl1xx4OOefUlLogi
aws.session.token=IQoJb3JpZ2luX2VjEPn//////////wEaCXVzLXdlc3QtMiJHMEUCIQCmdpevnO0J9iKo/mzmBoZt1t7h5X7ObwY+9NxbyHtmFgIgMRROEPNOJUyEmKr8iJqX/dc8bHsx5o2pcHKKtLykDD8qtwIIwv//////////ARAAGgw0Mjg3NDkyNjMyODYiDAzYdHh2vakQjzgvcSqLAnXWYOMMj1HQENz3mk2Ql2DIk4BBB3NRS/W3KAaTMXww7//YeUthryELZwtRUwArlW/m+hJtiIlCv9pqJ5p6riccc7T/7LlX9fZ7FsOrLec71XNr9ePrvdlNCp3ZKexuRPtcdqnYrfxw1VAXv09lY0Bj/KmN5RJKMhJ+ld6Q/no9kvvgnggaXY0NyIG+PsLvwvntBflHqnX+VYyQIFX5rEajz3JDCnqfPmEy9FmQzFyxg5nPMLZjzZKa7b+NWQ9MgZmZ2vUfHrz/652jVXWhKgjzHaO1xCYyBY6O34b1/U3G7GKlerUUO5Y3ShNp9lICIRlDUUSNQ5iV5w6aGW9hlW3DxSplDejs5OVsFDDqxp3RBjqdAfXY1B7wbClerjsjZyjgE13+gIyJpCmOQxdAZgYlwyZ2vqlWjtNRgQwWGDFhBSHotz45PMRWlvJD5xRyCDTQLcAGF8k3MHpYNe0p7iaxs65MGHhSl+Aba7/JSGqFv9WsKaa0jem/gFqFVtZY0lltU3OLF/C3PBTrDi8d0xsMZX5tWvLCLE9EgI85xJ2MB2e62f7NvY4lGfQR7yOmyrQ=

# El nombre del Bucket que creaste o vas a crear en AWS S3
aws.s3.bucket=guias-transportes-marco-2026