name: Java CI/CD con Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el codigo fuente
      uses: actions/checkout@v4

    - name: Configurar Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Compilar y empaquetar con Maven
     
      run: mvn clean package -DskipTests

    - name: Compartir el archivo JAR generado
      uses: actions/upload-artifact@v4
      with:
        name: gestion-guias-app
        path: target/*.jar